"""Added gamertag column to User table

Revision ID: 5cead63cf5a1
Revises: fe08d18379a1
Create Date: 2025-02-15 21:14:32.950724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cead63cf5a1'
down_revision = 'fe08d18379a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gamertag', sa.String(length=14), nullable=True))
        batch_op.create_unique_constraint('uq_gamertag', ['gamertag'])
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('gamertag')

    # ### end Alembic commands ###
